/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:8f46c10d-2a99-41d0-ba41-5735c883657e",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_TX7mpNADS",
    "aws_user_pools_web_client_id": "kd45heu9mmu86v52uv8js2b85",
    "oauth": {}
};


export default awsmobile;
